### ISSUE TITLE
 Can not accept asynchronous data

### ISSUE THREAD

**Issue by phobal** [MoePlayer/react-aplayer#2]
Hi,  
When I use it in my project, the music player list data asynchronously from the backend , so, I should update data when I got data, but you only handler to once in the componentDidMount life cycle, as a result, new data can not be updated, you should be in the componentWillReceiveProps life cycle update the music play instance props.  fake code as:  
``` js
  componentDidMount() {
    this.aplay(this.props);
  }
  componentWillReceiveProps(nextProps) {
    if (nextProps.music) {
      this.aplay(nextProps);
    }
  }
  aplay(props) {
    let ap = new APlayer({
      element: this.el,
      narrow: props.narrow,
      autoplay: props.autoplay,
      showlrc: props.showlrc,
      mutex: props.mutex,
      theme: props.theme,
      preload: props.preload,
      mode: props.mode,
      listmaxheight: props.listmaxheight,
      music: props.music
    });
```

**Comment by micooz** [comment]
Maybe you should save the aplayer instance to the component class and mutate it later whenever state changed:

```js
class YourComp extends Component {

  player = null;

  componentDidMount() {
    this.player = new APlayer({
      element: this.el,
      ...
  }

  componentWillReceiveProps(nextProps) {
    if (nextProps.music) {
      this.player.addMusic([...]);
    }
  }

}
```

**Comment by phobal** [comment]
@micooz you are right! If my method. resulting in multi aplayer instance，it's wrong, if your method, first in `componentDidMount` create a aplayer instance, then,after I get data from the backend in `componentWillReceiveProps `  use `this.player.addMusic([...])`, this seems to be no problem, but this.player instance must hava a `music` attribute, in componentDidMount, like this
``` js
this.player = new APlayer({
      element: this.el,
      ...
      music: {
        author:undefined,
        title: undefined,
        url: undefined,
        pic: undefined
      }
```
so, in aplayer instance contain a `undefined` music attribute, in componentWillReceiveProps use `this.player.addMusic([...]);`,only add music list to aplayer instance,  `undefined` music attribute still exist, so cann't resolve my problem,.

I found the aplayer API docs, it provide `ap.destroy()` method, so I do this
``` js
componentDidMount() {
    this.aplay(this.props);
  }
  componentWillReceiveProps(nextProps) {
    if (nextProps.music) {
      this.ap.destroy();  // after got new data, destroy aplayer instance
      this.aplay(nextProps);
    }
  }
  aplay(props) {
    this.ap = new APlayer({
      element: this.el,
      narrow: props.narrow,
      autoplay: props.autoplay,
      showlrc: props.showlrc,
      mutex: props.mutex,
      theme: props.theme,
      preload: props.preload,
      mode: props.mode,
      listmaxheight: props.listmaxheight,
      music: props.music
    });
```
What do you think？

**Comment by sabrinaluo** [comment]
@phobal Sorry for the late reply, I was on vacation during Christmas days, will check later

**Comment by phobal** [comment]
@sabrinaluo you're welcome , thanks

**Comment by sabrinaluo** [comment]
@phobal the original [aplayer](https://github.com/MoePlayer/APlayer) does not allow asynchronous data either.

In react app, you will have a render function to render the player right? something like this: https://github.com/MoePlayer/react-aplayer/blob/master/src/app.js#L22

What do you think about having some `if else` condition in the render function, and only when you get the callback data, should it render the player?

**Comment by phobal** [comment]
@sabrinaluo I think it is not friendly, Should be handle in Aplay Component, that reduce user's judgment.

**Comment by sabrinaluo** [comment]
@phobal the purpose of react-aplayer is just a wrapper of aplyer, exposing all the API from aplayer.
As per https://github.com/MoePlayer/APlayer/issues/124 , it does not support empty music list, and in the next version, there will be new API supporting changing music list.
